version: "3.8"
services:
  # 백엔드 서비스
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAEGER_ENDPOINT=http://jaeger:4318
      - PROMETHEUS_ENDPOINT=http://prometheus:9090
    networks:
      - monitoring
    restart: always
    depends_on:
      - jaeger
      - prometheus

  # 프론트엔드 서비스
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000" # 3000번 포트는 Grafana가 사용하므로 3001로 매핑
    environment:
      - BACKEND_URL=http://backend:8080
    networks:
      - monitoring
    restart: always
    depends_on:
      - backend

  # Node Exporter (호스트 시스템 모니터링)
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - "9101:9100"
    networks:
      - monitoring

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # Jaeger UI
      - "14252:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411" # Zipkin compatible endpoint
      - "4318:4318" # ✅ OTLP HTTP (OpenTelemetry)
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true # ✅ OTLP 활성화
      - COLLECTOR_OTLP_HTTP_PORT=4318 # ✅ OTLP HTTP 포트 지정 (선택적)
    networks:
      - monitoring

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: always

  # Grafana
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus
    restart: always

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
