global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8080"] # 백엔드 서비스 이름과 포트를 조정하세요

  # Node Exporter 설정 (호스트 시스템 메트릭)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
